/**
 * Market intel reporter — renders allocation as markdown.
 *
 * Sections:
 *   1. Headline summary (total budget, tier, channel rollup)
 *   2. Per-city allocation table
 *   3. Channel rollup table (which channels carry what % across all cities)
 *   4. Anti-patterns surfaced from channels JSON
 *   5. Action items (start LSA week 1, etc.)
 */

export function renderMarketIntelReport(allocation, opts = {}) {
  const { brand = 'Project', tier, antiPatterns = [], stormCities = [] } = opts;
  const lines = [];

  lines.push(`# ${brand} — Marketing Intel & Budget Allocation`, '');
  lines.push(`Generated ${new Date().toISOString().split('T')[0]} · tier: **${tier || 'auto'}**`, '');

  // 1. Summary
  lines.push('## Summary', '');
  lines.push(`- Total monthly budget: **$${allocation.totals.monthlyBudget.toLocaleString()}**`);
  lines.push(`- Cities covered: ${allocation.totals.cityCount}`);
  if (stormCities.length > 0) {
    lines.push(`- Storm override active in: ${stormCities.join(', ')}`);
  }
  lines.push('');

  // 2. Per-city table
  lines.push('## Per-City Allocation', '');
  lines.push('| City | $/mo | Top Channel | 2nd | 3rd |');
  lines.push('|---|---|---|---|---|');
  for (const c of allocation.byCity) {
    const top3 = c.perChannel.slice(0, 3);
    const cells = [
      c.city.name || c.city.id,
      `$${c.monthlyAllocation.toLocaleString()}`,
      top3[0] ? `${top3[0].channelName} ($${top3[0].dollars})` : '—',
      top3[1] ? `${top3[1].channelName} ($${top3[1].dollars})` : '—',
      top3[2] ? `${top3[2].channelName} ($${top3[2].dollars})` : '—',
    ];
    lines.push(`| ${cells.join(' | ')} |`);
  }
  lines.push('');

  // 3. Channel rollup
  lines.push('## Channel Rollup (across all cities)', '');
  lines.push('| Channel | $/mo | % of total |');
  lines.push('|---|---|---|');
  const totalBudget = allocation.totals.monthlyBudget;
  const sortedChannels = Object.entries(allocation.totals.perChannel).sort((a, b) => b[1] - a[1]);
  for (const [channelId, dollars] of sortedChannels) {
    const pct = totalBudget > 0 ? Math.round((dollars / totalBudget) * 100) : 0;
    lines.push(`| ${channelId} | $${dollars.toLocaleString()} | ${pct}% |`);
  }
  lines.push('');

  // 4. Per-city deep dive
  lines.push('## Per-City Detail', '');
  for (const c of allocation.byCity) {
    lines.push(`### ${c.city.name || c.city.id} — $${c.monthlyAllocation.toLocaleString()}/mo`);
    if (c.stormOverrideApplied) lines.push('_⚡ Storm override active_');
    if (c.city.factors) {
      const f = c.city.factors;
      lines.push('');
      lines.push(`Factors: demoFit ${pct(f.demoFit)} · searchVol ${pct(f.searchVolume)} · paidDensity ${pct(f.paidDensity)} · organicSat ${pct(f.organicSat)} · season ${pct(f.season)}`);
    }
    lines.push('');
    lines.push('| Channel | Score | $ / mo | % | Est. CPL |');
    lines.push('|---|---|---|---|---|');
    for (const ch of c.perChannel) {
      const cpl = ch.estimatedCpl ? `$${ch.estimatedCpl.low}-${ch.estimatedCpl.high}` : '—';
      lines.push(`| ${ch.channelName} | ${ch.score}/100 | $${ch.dollars.toLocaleString()} | ${Math.round((ch.share || 0) * 100)}% | ${cpl} |`);
    }
    lines.push('');
  }

  // 5. Anti-patterns
  if (antiPatterns.length > 0) {
    lines.push('## Hard Rules (do not violate)', '');
    for (const ap of antiPatterns) lines.push(`- ${ap}`);
    lines.push('');
  }

  // 6. Ramp playbook
  lines.push('## 90-Day Ramp Playbook', '');
  lines.push('1. **Week 1:** GBP optimized · LSA verification submitted · Google Search account scaffolded (branded + non-branded)');
  lines.push('2. **Weeks 2-4:** SEO city pages live · First Search spend · LSA awaiting approval');
  lines.push('3. **Weeks 5-8:** LSA active · Meta retargeting layer (pixel-warm visitors only) · Direct mail kit pre-staged');
  lines.push('4. **Weeks 9-12:** First storm response (if applicable): direct mail to NWS hail polygon + LSA bid lift + Search +50%');
  lines.push('5. **Months 4-6:** SEO break-even check · Reallocate 5-10pts from paid to content if organic delivers');
  lines.push('6. **Months 7-12:** YouTube + TikTok tests for Tier-3 luxury cities only');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('_Generated by RCBuild-Kit market-intel. Re-run after API state changes (Census ACS = annual, DataForSEO SERP = weekly recommended)._');

  return lines.join('\n') + '\n';
}

function pct(n) {
  if (typeof n !== 'number') return '—';
  return `${Math.round(n * 100)}%`;
}
